### ISSUE TITLE
make safer display scroll

### ISSUE THREAD

**Issue by GandelXIV** [GandelXIV/pidi-os#2]
In kdisplay_scroll() in drivers/display.c:
The function copies the row below the last one, assuming its zero. If some data gets written on the row bellow the last rendered, it will cause visual glitch.

**Comment by PQCraft** [comment]
@GandelXIV i made this scroll code for PhosphorOS, it can scroll up and down:
TMH = Lines (Text Mode Height)
TMW = Columns (Text Mode Width)
textmode_vbuf = text video array (0xB8000)
```c
void textmode_vscroll(int l) {
    if (!l) return;
    if (l > 0) {
        int y = 0;
        int e = TMH - l;
        while (y < e) {
            for (int x = 0; x < TMW; x++) {
                textmode_vbuf[x + y * TMW] = textmode_vbuf[x + (y + l) * TMW];
            }
            y++;
        }
        while (y < TMH) {
            for (int x = 0; x < TMW; x++) {
                textmode_vbuf[x + y * TMW] = TMC(fgc, bgc);
            }
            y++;
        }
    } else {
        l *= -1;
        int y = TMH - 1;
        int e = l - 1;
        while (y > e) {
            for (int x = 0; x < TMW; x++) {
                textmode_vbuf[x + y * TMW] = textmode_vbuf[x + (y - l) * TMW];
            }
            y--;
        }
        while (y > -1) {
            for (int x = 0; x < TMW; x++) {
                textmode_vbuf[x + y * TMW] = TMC(fgc, bgc);
            }
            y--;
        }
    }
}
```

**Comment by GandelXIV** [comment]
> @GandelXIV i made this scroll code for PhosphorOS, it can scroll up and down:
> TMH = Lines (Text Mode Height)
> TMW = Columns (Text Mode Width)
> textmode_vbuf = text video array (0xB8000)
> 
> ```c
> void textmode_vscroll(int l) {
>     if (!l) return;
>     if (l > 0) {
>         int y = 0;
>         int e = TMH - l;
>         while (y < e) {
>             for (int x = 0; x < TMW; x++) {
>                 textmode_vbuf[x + y * TMW] = textmode_vbuf[x + (y + l) * TMW];
>             }
>             y++;
>         }
>         while (y < TMH) {
>             for (int x = 0; x < TMW; x++) {
>                 textmode_vbuf[x + y * TMW] = TMC(fgc, bgc);
>             }
>             y++;
>         }
>     } else {
>         l *= -1;
>         int y = TMH - 1;
>         int e = l - 1;
>         while (y > e) {
>             for (int x = 0; x < TMW; x++) {
>                 textmode_vbuf[x + y * TMW] = textmode_vbuf[x + (y - l) * TMW];
>             }
>             y--;
>         }
>         while (y > -1) {
>             for (int x = 0; x < TMW; x++) {
>                 textmode_vbuf[x + y * TMW] = TMC(fgc, bgc);
>             }
>             y--;
>         }
>     }
> }
> ```

Thanks, i will take a look at it!
