### ISSUE TITLE
IRQs not working

### ISSUE THREAD

**Issue by GandelXIV** [GandelXIV/pidi-os#3]
In firmware/isr.c, irq_handler() never gets called (no idea why?)

**Comment by calebrwalk5** [comment]
do you still want help with this? i see the help wanted tag

**Comment by GandelXIV** [comment]
Yes, but they are not highest priority right now. I do not fully understand the way to implement them, so will have to do some more research.

**Comment by calebrwalk5** [comment]
> Yes, but they are not highest priority right now. I do not fully understand the way to implement them, so will have to do some more research.

ok, I will do some research and go through your headers to understand what you have going on. I am not entirely familiar with making an OS in C

**Comment by GandelXIV** [comment]
yeah me neither

**Comment by PQCraft** [comment]
@GandelXIV OK i have poked around a bit and something seems to be broken as your interrupts only fire once even when re-binding it and when using `-enable-kvm` it will crash (which is not supposed to change behavior) so something is incorrect.

**Comment by GandelXIV** [comment]
@PQCraft OK, i will check if its not some compilation or bootloader bug.

**Comment by GandelXIV** [comment]
Or maybe i will just rewrite it completly.

**Comment by GandelXIV** [comment]
Did some research and it seems to be a problem with the [GDT](https://github.com/GandelXIV/pidi-os/blob/main/boot/b32/32bit-gdt.asm).
